--
----HSQLDB
--create table users(
--	username varchar_ignorecase(50) not null primary key,
--	password varchar_ignorecase(50) not null,
--	enabled boolean not null
--);
--
--create table authorities (
--	username varchar_ignorecase(50) not null,
--	authority varchar_ignorecase(50) not null,
--	constraint fk_authorities_users foreign key(username) references users(username)
--);
--create unique index ix_auth_username on authorities (username,authority);
--
---- mysql
--create table users(
--	username VARCHAR(50) not null primary key,
--	password VARCHAR(50) not null,
--	enabled VARCHAR(5) not NULL
--);
--
--create table authorities (
--	username VARCHAR(50) not null,
--	authority VARCHAR(50) not null,
--	constraint fk_authorities_users foreign key(username) references users(username)
--);
--
--create unique index ix_auth_username on authorities (username,authority);
